[font]
normal = { family = "Terminus", style = "Regular" }
size = 10

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#CD0000"
green = "#00CD00"
yellow = "#CDCD00"
blue = "#0000EE"
magenta = "#CD00CD"
cyan = "#00CDCD"
white = "#E5E5E5"

[colors.bright]
black = "#7F7F7F"
red = "#FF0000"
green = "#00FF00"
yellow = "#FFFF00"
blue = "#5C5CFF"
magenta = "#FF00FF"
cyan = "#00FFFF"
white = "#FFFFFF"
